version: "3"

services:
  otel_collector:
    image: otel/opentelemetry-collector:0.13.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/dev/collector.yml:/etc/otel-collector-config.yaml:ro
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55680:55680"
      - "55681:55681"
      - "55679:55679"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250"

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
